format = "$os$username$hostname$memory_usage$shlvl$directory$fossil_branch$hg_branch$git_branch${custom.git_branch}$pijul_channel$git_status${custom.git_status}${custom.jj}$aws$buf$c$conda$crystal$dart$elixir$elm$fennel$golang$gradle$haskell$haxe$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$python$rlang$ruby$rust$scala$swift$zig $package$fill$status$direnv$docker_context$guix_shell$meson$nix_shell$time\n$character"
palette = "catppuccin_macchiato"

[aws]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "îŒ½  "

[buf]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "ï’ "

[c]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜ "

[conda]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "ï„Œ "

[crystal]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜¯ "

[custom.git_branch]
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"
format = "[$symbol$branch ]($style)"
style = ""
when = "! jj --ignore-working-copy root"

[custom.git_status]
command = "starship module git_status"
description = "Only show git_status if we're not in a jj repo"
format = "[$symbol$branch ]($style)"
style = ""
when = "! jj --ignore-working-copy root"

[custom.jj]
command = "jj log \\\n  --revisions @ \\\n  --no-graph \\\n  --ignore-working-copy \\\n  --color always \\\n  --limit 1 \\\n  --template '\n    separate(\" \",\n      change_id.shortest(4),\n      truncate_end(15, bookmarks, \"â€¦\"),\n      \"|\",\n      concat(\n        if(conflict, \"ğŸ’¥\"),\n        if(divergent, \"ğŸš§\"),\n        if(hidden, \"ğŸ‘»\"),\n        if(immutable, \"ğŸ”’\"),\n      ),\n      raw_escape_sequence(\"\\x1b[1;32m\") ++ if(empty, \"(empty)\"),\n      raw_escape_sequence(\"\\x1b[1;32m\") ++ coalesce(\n        truncate_end(29, description.first_line(), \"â€¦\"),\n        \"(no description set)\",\n      ) ++ raw_escape_sequence(\"\\x1b[0m\"),\n    )\n  '\n"
description = "The current jj status"
style = ""
symbol = "ï˜ "
when = "jj --ignore-working-copy root"

[dart]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜ "

[directory]
before_repo_root_style = "dimmed blue"
fish_style_pwd_dir_length = 1
format = "[$path ]($style)[$read_only]($read_only_style)"
read_only = " ó°Œ¾"
read_only_style = "red"
repo_root_style = "underline blue"
style = "fg:blue"
truncate_to_repo = false

[directory.substitutions]
Documents = "ó°ˆ™ "
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "

[direnv]
allowed_msg = "îª²"
denied_msg = "î©¶"
disabled = false
format = "[$symbol$loaded/$allowed ]($style)"
loaded_msg = "îª²"
not_allowed_msg = "î¬²"
style = "fg:mauve"
symbol = "ï» "
unloaded_msg = "î©¼"

[docker_context]
format = "[$symbol$context ]($style)"
style = "fg:mauve"
symbol = "ïŒˆ "

[elixir]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜­ "

[elm]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜¬ "

[fennel]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "îš¯ "

[fill]
style = "fg:surface1"
symbol = "-"

[fossil_branch]
format = "[$symbol$branch ]($style)"
style = "fg:green"
symbol = "ï˜ "

[git_branch]
disabled = true
format = "[$symbol$branch ]($style)"
style = "fg:green"
symbol = "ï˜ "

[git_status]
disabled = true
format = "[$all_status$ahead_behind ]($style)"
style = "fg:green"

[golang]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜§ "

[gradle]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î™  "

[guix_shell]
format = "[$symbol]($style)"
style = "fg:mauve"
symbol = "ïŒ¥ "

[haskell]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î· "

[haxe]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î™¦ "

[hg_branch]
format = "[$symbol$branch ]($style)"
style = "fg:green"
symbol = "ï˜ "

[hostname]
disabled = false
ssh_symbol = "î¬ "
style = "fg:#FFFFFF"

[java]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î‰– "

[julia]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜¤ "

[kotlin]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜´ "

[lua]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜  "

[memory_usage]
disabled = false
format = "[$symbol$ram( | $swap) ]($style)"
style = "fg:#FFFFFF"
symbol = "ó°› "

[meson]
format = "[$symbol$project ]($style)"
style = "fg:mauve"
symbol = "ó°”· "

[nim]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "ó°†¥ "

[nix_shell]
format = "[$symbol$state ]($style)"
style = "fg:mauve"
symbol = "ïŒ“ "

[nodejs]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "îœ˜ "

[ocaml]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î™º "

[os]
disabled = false
style = "fg:#FFFFFF"

[os.symbols]
AlmaLinux = "ïŒ "
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
RedHatEnterprise = "ïŒ– "
Redhat = "ïŒ– "
Redox = "ó°€˜ "
RockyLinux = "ïŒ« "
SUSE = "ïŒ” "
Solus = "ó° ³ "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
openSUSE = "ïŒ” "

[package]
disabled = true
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "ó°— "

[palettes.catppuccin_macchiato]
base = "#24273a"
blue = "#8aadf4"
crust = "#181926"
flamingo = "#f0c6c6"
green = "#a6da95"
lavender = "#b7bdf8"
mantle = "#1e2030"
maroon = "#ee99a0"
mauve = "#c6a0f6"
overlay0 = "#6e738d"
overlay1 = "#8087a2"
overlay2 = "#939ab7"
peach = "#f5a97f"
pink = "#f5bde6"
red = "#ed8796"
rosewater = "#f4dbd6"
sapphire = "#7dc4e4"
sky = "#91d7e3"
subtext0 = "#a5adcb"
subtext1 = "#b8c0e0"
surface0 = "#363a4f"
surface1 = "#494d64"
surface2 = "#5b6078"
teal = "#8bd5ca"
text = "#cad3f5"
yellow = "#eed49f"

[perl]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î™¾ "

[php]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î˜ˆ "

[pijul_channel]
format = "[$symbol$channel ]($style)"
style = "fg:green"
symbol = "ï˜ "

[python]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "îˆµ "

[rlang]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "ó°Ÿ” "

[ruby]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î‘ "

[rust]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î¨ "

[scala]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "îœ· "

[shlvl]
disabled = false
format = "[$shlvl ]($style)"
style = "fg:#FFFFFF"
threshold = 5

[status]
disabled = false
format = "[$symbol$status ]($style)"
style = ""

[swift]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "î• "

[time]
disabled = false
format = "[$time ]($style)"
style = "fg:overlay1"
time_format = "%R"

[username]
disabled = true
format = "[$user ]($style)"
show_always = true
style_root = "fg:#FFFFFF"
style_user = "fg:#FFFFFF"

[zig]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "îš© "
