format = "$os$username$hostname$memory_usage$shlvl$directory$fossil_branch$hg_branch$git_branch$pijul_channel$git_status $aws$buf$c$conda$crystal$dart$elixir$elm$fennel$golang$gradle$haskell$haxe$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$python$rlang$ruby$rust$scala$swift$zig$package$fill$status$direnv$docker_context$guix_shell$meson$nix_shell$time\n$character"
palette = "catppuccin_macchiato"
[aws]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "  "

[buf]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[c]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[conda]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[crystal]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[dart]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[directory]
before_repo_root_style = "dimmed blue"
fish_style_pwd_dir_length = 1
format = "[$path ]($style)[$read_only]($read_only_style)"
read_only = " 󰌾"
read_only_style = "red"
repo_root_style = "underline blue"
style = "fg:blue"
truncate_to_repo = false

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[direnv]
allowed_msg = ""
denied_msg = ""
disabled = false
format = "[$symbol$loaded/$allowed ]($style)"
loaded_msg = ""
not_allowed_msg = ""
style = "fg:mauve"
symbol = " "
unloaded_msg = ""

[docker_context]
format = "[$symbol$context ]($style)"
style = "fg:mauve"
symbol = " "

[elixir]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[elm]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[fennel]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[fill]
style = "fg:surface1"
symbol = "-"

[fossil_branch]
format = "[$symbol$branch ]($style)"
style = "fg:green"
symbol = " "

[git_branch]
format = "[$symbol$branch ]($style)"
style = "fg:green"
symbol = " "

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "fg:green"

[golang]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[gradle]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[guix_shell]
format = "[$symbol]($style)"
style = "fg:mauve"
symbol = " "

[haskell]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[haxe]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[hg_branch]
format = "[$symbol$branch ]($style)"
style = "fg:green"
symbol = " "

[hostname]
disabled = false
ssh_symbol = " "
style = "fg:#FFFFFF"

[java]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[julia]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[kotlin]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[lua]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[memory_usage]
disabled = false
format = "[$symbol$ram( | $swap) ]($style)"
style = "fg:#FFFFFF"
symbol = "󰍛 "

[meson]
format = "[$symbol$project ]($style)"
style = "fg:mauve"
symbol = "󰔷 "

[nim]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "󰆥 "

[nix_shell]
format = "[$symbol$state ]($style)"
style = "fg:mauve"
symbol = " "

[nodejs]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[ocaml]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[os]
disabled = false
style = "fg:#FFFFFF"

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
RockyLinux = " "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
openSUSE = " "

[package]
disabled = true
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "󰏗 "

[palettes.base16]
base00 = "#24273a"
base01 = "#1e2030"
base02 = "#363a4f"
base03 = "#494d64"
base04 = "#5b6078"
base05 = "#cad3f5"
base06 = "#f4dbd6"
base07 = "#b7bdf8"
base08 = "#ed8796"
base09 = "#f5a97f"
base0A = "#eed49f"
base0B = "#a6da95"
base0C = "#8bd5ca"
base0D = "#8aadf4"
base0E = "#c6a0f6"
base0F = "#f0c6c6"
base10 = "#24273a"
base11 = "#24273a"
base12 = "#ed8796"
base13 = "#f5a97f"
base14 = "#a6da95"
base15 = "#8bd5ca"
base16 = "#8aadf4"
base17 = "#c6a0f6"
black = "#24273a"
blue = "#8aadf4"
bright-black = "#494d64"
bright-blue = "#8aadf4"
bright-cyan = "#8bd5ca"
bright-green = "#a6da95"
bright-magenta = "#c6a0f6"
bright-orange = "#f5a97f"
bright-purple = "#c6a0f6"
bright-red = "#ed8796"
bright-white = "#b7bdf8"
bright-yellow = "#eed49f"
brown = "#f0c6c6"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#c6a0f6"
orange = "#f5a97f"
purple = "#c6a0f6"
red = "#ed8796"
white = "#cad3f5"
yellow = "#eed49f"

[palettes.catppuccin_macchiato]
base = "#24273a"
blue = "#8aadf4"
crust = "#181926"
flamingo = "#f0c6c6"
green = "#a6da95"
lavender = "#b7bdf8"
mantle = "#1e2030"
maroon = "#ee99a0"
mauve = "#c6a0f6"
overlay0 = "#6e738d"
overlay1 = "#8087a2"
overlay2 = "#939ab7"
peach = "#f5a97f"
pink = "#f5bde6"
red = "#ed8796"
rosewater = "#f4dbd6"
sapphire = "#7dc4e4"
sky = "#91d7e3"
subtext0 = "#a5adcb"
subtext1 = "#b8c0e0"
surface0 = "#363a4f"
surface1 = "#494d64"
surface2 = "#5b6078"
teal = "#8bd5ca"
text = "#cad3f5"
yellow = "#eed49f"

[perl]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[php]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[pijul_channel]
format = "[$symbol$channel ]($style)"
style = "fg:green"
symbol = " "

[python]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[rlang]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = "󰟔 "

[ruby]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[rust]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[scala]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[shlvl]
disabled = false
format = "[$shlvl ]($style)"
style = "fg:#FFFFFF"
threshold = 5

[status]
disabled = false
format = "[$symbol$status ]($style)"
style = ""

[swift]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "

[time]
disabled = false
format = "[$time ]($style)"
style = "fg:overlay1"
time_format = "%R"

[username]
disabled = true
format = "[$user ]($style)"
show_always = true
style_root = "fg:#FFFFFF"
style_user = "fg:#FFFFFF"

[zig]
format = "[$symbol($version) ]($style)"
style = "fg:peach"
symbol = " "
